// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhnhxqyjsxgaqkypbxgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZobmh4cXlqc3hnYXFreXBieGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTUwODEsImV4cCI6MjA3Mjc5MTA4MX0.jbdpI4FQys_5R7TQtKPF4Aqbeg6AixvFa5BmRpbQOI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});